setAxProps = @(ax) set(ax, 'View'              , [-140,20]    , ...
                           'PlotBoxAspectRatio', [2,2,1]      , ...
                           'Projection'        , 'Perspective', ...
                           'Box'               , 'on'         , ...
                           'XLimSpec'          , 'tight'      , ...
                           'YLimSpec'          , 'tight'      , ...
                           'ZLimSpec'          , 'tight'      );

figure('Position', [0,0,800,500])
plotToolbar(model.G, states, 'field', 'pressure'); 
colormap(jet); colorbar; 
plotWell(G, W,'height',0);
setAxProps(gca); 
set(gca,'FontSize',12);
plotWellSols(wellSols, schedule.step.val);
